name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: dev
      FDB_VERSION: ${{ matrix.fdb }}
    name: Lint
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        elixir: ["1.19"]
        otp: ["28"]
        fdb: ["7.3.69"]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
          rebar3-version: "3"
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_
      - uses: actions/cache@v3
        with:
          path: _build/dev/*.plt
          key: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-plt_${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-plt_
      - name: Cache FoundationDB packages
        id: cache-fdb-lint
        uses: actions/cache@v3
        with:
          path: /tmp/fdb-debs
          key: fdb-clients-${{ matrix.fdb }}
      - name: Download FoundationDB packages
        if: steps.cache-fdb-lint.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/fdb-debs
          wget --quiet -O /tmp/fdb-debs/foundationdb-clients_${FDB_VERSION}-1_amd64.deb \
            https://github.com/apple/foundationdb/releases/download/${FDB_VERSION}/foundationdb-clients_${FDB_VERSION}-1_amd64.deb
      - name: Install FoundationDB
        run: sudo dpkg -i /tmp/fdb-debs/foundationdb-clients_${FDB_VERSION}-1_amd64.deb
      - run: mix deps.get
      - run: mix lint

  test:
    runs-on: ${{ matrix.os }}
    name: Test Elixir ${{ matrix.elixir }}, OTP ${{ matrix.otp }}, OS ${{ matrix.os }}, FDB ${{ matrix.fdb }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        elixir: ["1.19"]
        otp: ["28"]
        fdb: ["7.3.69"]
    env:
      MIX_ENV: test
      FDB_VERSION: ${{ matrix.fdb }}
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_
      - name: Cache FoundationDB packages
        id: cache-fdb-test
        uses: actions/cache@v3
        with:
          path: /tmp/fdb-debs
          key: fdb-${{ matrix.fdb }}
      - name: Download FoundationDB packages
        if: steps.cache-fdb-test.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/fdb-debs
          wget --quiet -O /tmp/fdb-debs/foundationdb-clients_${FDB_VERSION}-1_amd64.deb \
            https://github.com/apple/foundationdb/releases/download/${FDB_VERSION}/foundationdb-clients_${FDB_VERSION}-1_amd64.deb
          wget --quiet -O /tmp/fdb-debs/foundationdb-server_${FDB_VERSION}-1_amd64.deb \
            https://github.com/apple/foundationdb/releases/download/${FDB_VERSION}/foundationdb-server_${FDB_VERSION}-1_amd64.deb
      - name: Install FoundationDB
        run: |
          sudo dpkg -i /tmp/fdb-debs/foundationdb-clients_${FDB_VERSION}-1_amd64.deb
          sudo dpkg -i /tmp/fdb-debs/foundationdb-server_${FDB_VERSION}-1_amd64.deb
      - run: mix deps.get --only test
      - run: mix deps.compile
      - run: mix compile
      - run: mix test
